name: Run Continuous Integration Golang App

on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - 'master'

jobs:
  testing:
    runs-on: ubuntu-latest
    name: 'Run unit test and lint'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run unit test
        run: go test -v ./...
      - name: Run linter with golangci-lint
        uses: golangci/golangci-lint-action@v3

  build:
    runs-on: ubuntu-latest
    name: 'Run golang build'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: test build golang
        run: go build -o ./build/main .
